development:
  adapter: mysql2
  database: rcaptcha
  host: localhost
  username: root
  password: Dips
  # socket: /tmp/mysql.sock
production:
  adapter: mysql2
  database: rcaptcha_production
  pool: 15
  host: localhost
  username: root 
  password: 
